version: "3"

services:
  courier:
    image: ${DOCKER_IMAGE_NAME:-ilhasoft/courier}:${DOCKER_IMAGE_TAG:-latest}
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - 8080:8000
